# Generated by Django 4.0.4 on 2022-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='title',
            new_name='model_produto',
        ),
        migrations.AddField(
            model_name='produtos',
            name='color',
            field=models.CharField(choices=[('B', 'Blue'), ('B', 'Black'), ('W', 'White'), ('B', 'Red')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3),
        ),
    ]
