# Generated by Django 4.0.4 on 2022-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='color',
            field=models.CharField(choices=[('B', 'Blue'), ('Bk', 'Black'), ('W', 'White'), ('R', 'Red')], max_length=3),
        ),
    ]
