# Generated by Django 4.0.4 on 2022-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produtos_id_produto_produtos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='price',
            field=models.IntegerField(),
        ),
    ]
