# Generated by Django 4.0.4 on 2022-04-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtos_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='model_produto',
            new_name='title',
        ),
    ]
