# Generated by Django 4.0.4 on 2022-04-30 21:01

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_rename_model_produto_produtos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=produtos.models.upload_image_produto),
        ),
    ]
