# Generated by Django 4.0.4 on 2022-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_remove_produtos_id_produtos_id_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='id_shirt',
        ),
        migrations.AddField(
            model_name='produtos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
