# Generated by Django 4.0.4 on 2022-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_remove_produtos_id_produtos_id_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('red', 'Red')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extralarge', 'Extra Large')], max_length=10),
        ),
    ]
