# Generated by Django 4.0.4 on 2022-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produtos_slug_alter_produtos_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='produtos',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
